### ISSUE TITLE
circular dependency on scikit-build in the setup process

### ISSUE THREAD

**Issue by mbkumar** [BartoszBartmanski/StoSpa2#4]
StoSpa2 can not be installed with the way the setup.py file is written unless someone installs scikit-build before trying to install pystospa with either `pip install pystospa` or `python setup.py install`.

Either update the documentation or remove the cyclic dependency on scikit-build.

#openjournals/joss-reviews#2293

**Comment by BartoszBartmanski** [comment]
I removed the circular dependency on scikit-build by removing it from install_requires argument within setup.py and adding an instruction to README and the online documentation to install scikit-build before installing pystospa
