### ISSUE TITLE
Optional dependency on matplotlib

### ISSUE THREAD

**Issue by mbkumar** [BartoszBartmanski/StoSpa2#5]
Though not a strict dependency, matplotlib is needed to run the python example.  I'd suggest to mention the dependency in the README or in fact add it to setup.py in order not to trip beginners. Based on my experience, you will encounter many users not at all familiar with python.

#openjournals/joss-reviews#2293

**Comment by BartoszBartmanski** [comment]
A note has been added in the README and the documentation that numpy and matplotlib are needed to run the python examples, as well as a command to install those dependencies if one wishes to run those examples. I chose not to add these dependencies to setup.py to keep the number of dependencies as low as possible.
